---
title: "Imputation Methods for Prediction"
author: "Paul Harmon"
date: "January 5, 2018"
output: 
  beamer_presentation:
    theme: "AnnArbor"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Introduction
## Missing Data

Most of the fields used in the predictive models we want to fit contain missing values. This can be a major issue for several reasons: 

+ For some fields,more data may be missing than are available
+ Some methods fail with missing data, limiting our options for analysis
+ Reproducibility: Even if data are available now, 

## Types of Missing Data

__Missing Completely at Random__: If this is the case, the missingness problem is somewhat mitigated. Usually, if the data are missing at random, we do not worry about missing important subsets of the population because we assume that at least some of those observations are occuring. ( _This is unlikely in practice_ )

__Missing At Random__: A more reasonable assumption, we assume that the observation is not more likely to be missing after controlling for the other variables. In this case, we can use the other variables to predict the missing variable values given that we know other things about them. 

_Example: Say we know low income students are less likely to report HS GPA values than high income students_.  

__Systematic Missingness__: A more likely scenario, where data are more likely to be missing for some subpopulations than for others. In this case, ignoring the problem may lead to skewed inferences/results because we have missing information that is tied to some endogenous part of the process we are trying to predict. _The key aspect of missingness not at random is that something 

_Example: Banner information for a subset of students were mis-entered or certain fields ignored by whoever added information in._

## Handling Missing Data


# Methods

## Complete Case Analysis
The idea here is to simply ignore observations if they have missing data. In R, this is the default method used. If you only have a few missing observations and you have a lot of data, this may be reasonable. 

In cases where data are MCAR, Complete Case analysis provides unbiased results (although it is a bit inefficient since you essentially throw away data). However, if the data are only MAR or are systematically missing, inferences tend to be biased. 

##Imputation

Imputation refers to the strategy of replacing missing values with a number. This may be as simple as adding the mean of the observed data or can involve more complicated methods. 

+ __Mean-based Imputation__: Replace all missing values the mean of the data that were observed. 
+ __Single Conditional Imputation__: Estimate the mean from a subgroup of the data (i.e. condition the imputed value on the known covariates). Single imputation generates just a single value.  
+ __Multiple Conditional Imputation__: Similar to Single Imputation, but rather than estimating just one value, you estimate a _distribution_ of values that the missing value could take. Research via simulation studies indicates that this method gives more appropriate standard errors than single imputation. 


## Previous Research
Methods for imputation have been compared often in the literature. Often, differences have proven to be fairly  

# Model


# Results

# Discussion